### ISSUE TITLE
Erroneous Redirect Causing Infinite Modal Loop  Description

### ISSUE THREAD

**Issue by shayaulman** [emargareten/inertia-modal#12]
Hi, first thanks for the useful package!

I encountered the following issue:
If the modal is closed and reopened before the URL adjusts to the redirect route, the redirect function targets the modal resulting in a cyclic redirect issue, thus the modal cannot be closed.

**Comment by emargareten** [comment]
Fixed in [v0.1.0](https://github.com/emargareten/inertia-modal/releases/tag/v0.1.0)

Please feel free to update your package, test it in your project, and let me know if everything is working as expected now. If you encounter any further issues or have additional feedback, don't hesitate to open a new issue, and I'll be happy to assist.
